env:
  browser: true
  es2021: true
  jest: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always